### ISSUE TITLE
Python failure when writing BITS results

### ISSUE THREAD

**Issue by ricardon** [01org/luv-yocto#73]
Somethimes the following error is observed when BITS is writing the cpio archive

Batch mode complete

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/boot/python/init.py", line 246, in init
    redirect.write_logfile_cpio("/boot/bitsrd", "home/root/bits-log.txt")
  File "/boot/python/redirect.py", line 95, in write_logfile_cpio
    _bits.disk_write(f, sector, offset,
logdata[bytes_written:bytes_written+leng
th])
IOError: [Errno 15] GRUB error 15

**Comment by ricardon** [comment]
GRUB error 15 is GRUB_ERR_WRITE_ERROR. It has been observed in certain USB sticks.
